### ISSUE TITLE
Internal error when configuration plugin

### ISSUE THREAD

**Issue by undigo** [AlphaNodes/redmine_privacy_terms#1]
I install your plugin but when I go to configuration of this , a 404 page appears.
DB migration is right also.
A difficult interpretation of method `auto_complete_project_path' ?

can you find a fix ?
Regards,

here log error 
Started GET "/settings/plugin/redmine_privacy_terms" for XXX.XXX.XXX.XXX at 2018-05-30 22:03:54 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_privacy_terms"}
  Current user: user (id=1)
  Rendered plugins/redmine_privacy_terms/app/views/redmine_privacy_terms/settings/_cookie_agreement.html.slim (95.4ms)
  Rendered plugins/redmine_privacy_terms/app/views/redmine_privacy_terms/settings/_terms.html.slim (363.7ms)
  Rendered common/_tabs.html.erb (478.0ms)
  Rendered plugins/redmine_privacy_terms/app/views/redmine_privacy_terms/settings/_settings.html.slim (500.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (505.6ms)
Completed 500 Internal Server Error in 537ms (ActiveRecord: 3.6ms)

ActionView::Template::Error (undefined method `auto_complete_project_path' for #<#<Class:0x00005570ba42be10>:0x00005570ba1c1058>
Did you mean?  autocomplete_projects_path
               auto_complete_issues_path
               auto_complete_select_entries
               autocomplete_project_memberships_path
               auto_complete_issues_url
               autocomplete_projects_url):
     7: 
     8:   p
     9:     = label_tag 'settings[terms_project_id]', l(:label_project)
    10:     = auto_complete_select_entries('settings[terms_project_id]',
    11:                                    'project',
    12:                                    (@settings[:terms_project_id].present? ? Project.find(@settings[:terms_project_id]) : nil))
    13: 
  plugins/additionals/lib/additionals/helpers.rb:270:in `auto_complete_select_entries'
  plugins/redmine_privacy_terms/app/views/redmine_privacy_terms/settings/_terms.html.slim:10:in `_26ba2ad016890b68d97bd7f723223196'
  app/views/common/_tabs.html.erb:17:in `block in _1729100605e4d3d85bef8d00f14b503b'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_1729100605e4d3d85bef8d00f14b503b'
  app/helpers/application_helper.rb:345:in `render_tabs'
  plugins/redmine_privacy_terms/app/views/redmine_privacy_terms/settings/_settings.html.slim:2:in `_b18dcb1fb6a07bb4ca150e943e042ec3'
  app/views/settings/plugin.html.erb:6:in `block in _d5f01f813749aff256bee7ef5fb8a072'
  app/views/settings/plugin.html.erb:4:in `_d5f01f813749aff256bee7ef5fb8a072'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

my Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.11
  clipboard_image_paste          1.12
  computed_custom_field          1.0.6
  disable_activity               0.0.1
  event_notifications            2.4.1
  redmine_banner                 0.1.2
  redmine_ckeditor               1.1.5
  redmine_custom_css             0.1.7
  redmine_custom_reports         0.1.5
  redmine_drafts                 0.2.0
  redmine_issue_templates        0.1.8
  redmine_landing_page           0.1.1
  redmine_logs                   0.1.1
  redmine_privacy_terms          1.0.0

**Comment by alexandermeindl** [comment]
Thanks for this feedback, I'll take a look at it.

**Comment by alexandermeindl** [comment]
The problem should be gone with my last commit. Please try it with the latest code and let me know, if everything works as expected.

cu alex

**Comment by undigo** [comment]
after update the last commit and restart apache server, the setting option is fixed.

Thanks for your quick update 👍
