### ISSUE TITLE
howto limit the permission user visibility ?

### ISSUE THREAD

**Issue by undigo** [AlphaNodes/redmine_privacy_terms#2]
all my roles are default permission to visibility from redmine core.
But I have KO in inspect tab of Number of user-visibility all : 

User role visibility all 👎 
Roles with user visibility ALL - make sure if this is really necessary.

What can I do it to limit the permission in role ?
I can give only two mode in role : full visibility of all active users or visibility of members users in visible project 

thanks

**Comment by ClaudiaMeindl** [comment]
Hi, it's your decision if you set the user visibility to All (depends on your use case), if you really think it is necessary in your system so leave it. We just make recommendations. 

We have updated the information for INSPECTORS and implemented an example on how user visibility ALL works. This should answer your question: https://github.com/alphanodes/redmine_privacy_terms/blob/master/INSPECTORS.md#user-role-visibility-all

**Comment by undigo** [comment]
Thanks for you detail page.
My use case is to not permitted users visibility between them, but Redmine not have functionality to add "not visibility members" in role.
If just visibility of group can be possible in role, it’s just necessary. 
What I need to limit impact for privacy users is to not permitted users see another users in same project but only group for assignee field



Cordialement,

Eric MAILLARD
CEO

undigo.fr <https://undigo.fr/>

**Comment by ClaudiaMeindl** [comment]
Ok. The plugin simple covers up possible problems. It does not mean you have to fix it. In your case you have anyway no other choice than leave it the way it is. :)
I think you can close this issue then. 
Greetings 
Claudia
