### ISSUE TITLE
unable to show privacy & terms

### ISSUE THREAD

**Issue by cformisano** [AlphaNodes/redmine_privacy_terms#3]
Dear All,
I use redmine 3.4.4 and, even if I have enabled the privacy and term tab (added the wiki page link with the two buttons and the page for the reject response) I cannot see the message for the (not administrator) users. May you help me?

**Comment by alexandermeindl** [comment]
Make sure you assigned existing wiki pages in the configuration for terms AND reject page. If these two wiki pages exists, you'll see a link called "Show" behind the input fields. Only if these to pages really exist (to make sure there is no misbehavior) users get displayed the terms page.

I hope, I could help you with this information.
