### ISSUE TITLE
Conflict with forced password update

### ISSUE THREAD

**Issue by 3e-maciej** [AlphaNodes/redmine_privacy_terms#4]
When user did not accept terms and administrator forces password change upon next login or there is automatic password change every X days enabled - browser enters infinite redirects loop between terms page and "my_password_path".

You should consider adding "my_password_path" to allowed paths in application_controller_patch.rb.

**Comment by alexandermeindl** [comment]
Hi @3e-maciej 

somehow I missed this issue. Thanks for pointing this out! I added my_password_path to allowed paths with my last commit.
